### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#169]
Add a composer.json file so you can add this project as a dependency in PHP projects.

**Comment by JBCSU** [comment]
@sherakama I was able to use composer to include decanter in my WordPress theme without changing anything in this repo. Here are the relevant bits of my themes' `composer.json`:

```
  "repositories": [
    {
      "type": "composer",
      "url": "https://wpackagist.org"
    },
    {
      "type": "package",
      "package": {
        "name": "stanford/decanter",
        "version": "3.0.0",
        "source": {
          "type": "git",
          "url": "git@github.com:SU-SWS/decanter.git",
          "reference": "origin/master"
        }
      }
    }
  ],
  "require": {
    "timber/timber": "^1.7",
    "stanford/decanter": "3.0.*"
  },
```

So that's all lovely, except installing decanter with composer as above does not also include Decanter's dependencies, e.g. Bourbon, Neat, normalize, ....

Is there a goal of creating a completely self-contained `decanter.scss`, or will we require anyone who builds on top of decanter to use npm in order to get decanter's dependencies?

**Comment by sherakama** [comment]
composer.json is available.
