### ISSUE TITLE
Automate Accessibility Testing

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#174]
**Is your feature request related to a problem? Please describe.**

Read through:
https://www.previousnext.com.au/blog/automate-your-drupal-accessibility-testing-axe-and-nightwatchjs

**Describe the solution you'd like**
Plan and design an implementation that could work with Decanter.

**Describe alternatives you've considered**
None yet. Research is needed.

**Additional context**
This is a nice to have.

**Comment by cjwest** [comment]
@sherakama,
I like this approach since you can couple the tests with modules. I like that because it is not dependent on external tools. I wonder how comprehensive it is and if it would be hard to maintain? 

From a broader perspective, there are a bunch of great tools for doing accessibility testing.
I think that we should take a look at each of these tools and approaches to see where there is overlap and where one tool works better than another, and of course what works best with our process.

**Comment by sherakama** [comment]
That sounds like a good idea. Please document the possible tools and your recommendation in this ticket.

**Comment by buttonwillowsix** [comment]
Find out if vendor/Jiatyan are available.

**Comment by buttonwillowsix** [comment]
For Decanterpalooza 2, dovetail this work with the following 2 tickets:
https://stanfordits.atlassian.net/browse/SOEOP-41
https://stanfordits.atlassian.net/browse/THEME-13

**Comment by buttonwillowsix** [comment]
@yvonnetangsu were you thinking about something like this? https://gist.github.com/jonathantneal/a9b8901273475d261dd3

**Comment by buttonwillowsix** [comment]
@cjwest maybe some of the text from this ticket: https://stanfordits.atlassian.net/browse/SOEOP-41 would be great to include in a modified on the Decanter wiki?

**Comment by buttonwillowsix** [comment]
This could also be done as a function like so:
https://jonsuh.com/blog/organizing-z-index-with-sass/

**Comment by buttonwillowsix** [comment]
Moved to holding until D8 release.

**Comment by buttonwillowsix** [comment]
Many of the related jira tickets are done, so post-D8 release, let's see what still needs doing.
