### ISSUE TITLE
Modular spacing helpers to match grid gutter

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#282]
Update the modular spacing mixins to match the gutters

**Comment by sherakama** [comment]
Updated modular spacing to match: https://user-images.githubusercontent.com/8933670/51643316-e309de00-1f20-11e9-969a-7ae188d9e7ae.png

**Comment by yvonnetangsu** [comment]
Talked to John today and got some clarification on modular spacing:

- Modular spacing and modular typography use totally different system to calculate the steps, even though they share the same base value at each breakpoint.
- Modular typography follows the Bourbon modular-scale mixin formula with a 1.25 scale ratio between each step, ie - 
modular-scale(0) = $base-value
modular-scale(1) = $base-value * 1.25
modular-scale(2) = $base-value * 1.25 * 1.25 etc
- Modular spacing does NOT use the above system. There is no fix scale ratio value. Instead, the scale is manually adjusted by John and Kerri because they needed more granular control over the spacing values. This scale is documented in Figma.

**Comment by yvonnetangsu** [comment]
![screen shot 2019-01-25 at 11 00 46 am](https://user-images.githubusercontent.com/42749717/52239330-0a4a9e80-2883-11e9-80aa-e786e7d2c0d0.png)

**Comment by sherakama** [comment]
Ok, I am going to close this ticket as it is incorrect. We do not want matching values for gutters and element spacing. Work in https://github.com/SU-SWS/decanter/pull/290 and https://github.com/SU-SWS/decanter/issues/288 should take care of things.
