### ISSUE TITLE
target @mixin sticky-footer to .site-footer selector instead of .global-footer; change su-global-footer component to <section> rather than <footer>

### ISSUE THREAD

**Issue by stocker** [SU-SWS/decanter#298]
**Is your feature request related to a problem? Please describe.**
@mixin sticky-footer targets .global-footer, which means that only the red global footer gets pinned to the bottom of the window.  Targeting the <footer> element instead means that the entire footer, including site-specific footer, will get pinned to bottom of window.

**Describe the solution you'd like**
Change @mixin sticky-footer to target the <footer> selector.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by sherakama** [comment]
Targeting an HTML tag would be difficult. We would not want to affect all `<footer>` elements but rather only the one at the bottom of the page. We also, cannot assume where in the DOM this element will be. It could be a direct child of `<body>` or it could be a number of children deeper. 

Perhaps we flip this problem on its head and make the sticky footer its own CSS class that the site builder can add to their site and add a variant for the global footer so that the default is not sticky.

**Comment by stocker** [comment]
good thought.  Should I adjust to <footer class="sticky-footer"> and target the mixin to .sticky-footer?  I may also need some guidance on how to commit to a pending pull-request.

**Comment by stocker** [comment]
changed sticky-footer mixin to target ".page-footer" class by default rather than  <footer> element.  selector can be overridden as well.

**Comment by stocker** [comment]
these changes have been merged into master.  closing this issue.
