### ISSUE TITLE
Add more linking option for card component

### ISSUE THREAD

**Issue by yvonnetangsu** [SU-SWS/decanter#352]
Our card component currently only allow linking either with the button or the CTA action link which are both optional fields. Looking at website patterns, It is fairly common that the card headline, card image, or even the whole card is used as a link. Perhaps we can make it configurable by putting logic in the twig template. 

Note: One card should be allowed to link to one single URL, e.g., we can't have the image link to one URL and the button link to another.

**Comment by buttonwillowsix** [comment]
@yvonnetangsu and @kerri-augenstein adding "Needs Design" to this according to our spreadsheet!

**Comment by kerri-augenstein** [comment]
@yvonnetangsu we may want to think through this a little more, as if we allow for an optional cta-text-link, and a button, and a title, and an image... how will the user, on the authoring side decide which to link? OR, are you suggesting that the twig template allow for the linking, and that on the CMS-side, we get concrete about how to handle the user experience?

**Comment by yvonnetangsu** [comment]
@kerri-augenstein, I imagine that there might be different ways that these cards can be created by the user and how linking can be handled? For example, in WordPress, we could use shortcodes to pass on different parameters to generate an item. Let's use a completely made up example - the user enters the shortcode in a WYSIWYG editor
`[card link="headline" orientation="vertical" title="I'm a Card" content="lorem ipsum" url="https://www..."]` 
and then the CMS will generate the markup for the card based on that input. In this case, since `link="headline"` is entered, `"link headline" = true` is passed onto the twig template which has some logic built in, and the CMS will output HTML that adds a link tag around the headline. 

And I imagine there might be other way in Drupal to create a card - maybe a custom Drupal module that provide extra linking options (checkboxes?)? Using https://engineering.stanford.edu/ as an example, some of the cards have headline and image links, without an explicit CTA link at the bottom or a button - so that's what I had in mind, to provide options for those cases.

Let me know if you'd like me to clear things up further 😄

**Comment by yvonnetangsu** [comment]
@sherakama , tagging you in case you have anything to add in response to Kerri's question.

**Comment by sherakama** [comment]
The pattern to link the whole card is common and recommended for accessibility reasons. You do not want to have a scenario where there are multiple links with the same destination near each other in the DOM. I am fine with either defined logic or a user option.

**Comment by kerri-augenstein** [comment]
@sherakama @yvonnetangsu all sounds great, so it just sounds like we may need to get nitty-gritty on the fields in this guy. 

I would assume: 
—we will want to limit the wysiwyg on the CMS side (to eliminate the option for adding an <a> into the body) 
—and we would want to have a radio selection for which a user wants, a button or a CTA text link 

And we would need to think through the interaction for... 
—a linked title: how would a user enter the url for this? or tell the system that they want the title to display as a link if that's a variable option (aka, it can be a link or not) 

I'm also assuming we can make some hard rules around these things that we have not currently decided upon, if that solves a problem. Aka, if the title **cannot** link because it causes too many weirdness-es, that's fine with me. We'll solve together. 

The image and card background, all getting an interaction state and linking together when clicked sounds great. 

@buttonwillowsix do you think we can have a ticket for some dedicated time on this challenge during the first or second day of our sprint? Think that's a good way to deal with this?

**Comment by buttonwillowsix** [comment]
@kerri-augenstein I could schedule some time for a subset of folks to discuss this in the early afternoon on the first day?

**Comment by kerri-augenstein** [comment]
That sounds great @buttonwillowsix

**Comment by kerri-augenstein** [comment]
okay @sherakama @yvonnetangsu ... playing devil's advocate now, as I think through some use cases. What if the author wanted a card that had a title, body, and two cta-text-links. Or even a list of links. Would that need to be an entirely separate type of card? (which would be fine with me. In fact, it might be nice to have a cta-list card that has "add-another", no title-link, no image linking, and no background-card linking)... thoughts?

**Comment by yvonnetangsu** [comment]
> okay @sherakama @yvonnetangsu ... playing devil's advocate now, as I think through some use cases. What if the author wanted a card that had a title, body, and two cta-text-links. Or even a list of links. Would that need to be an entirely separate type of card? (which would be fine with me. In fact, it might be nice to have a cta-list card that has "add-another", no title-link, no image linking, and no background-card linking)... thoughts?

Yeah, I've seen that also (a link list card?). Seems nice to have as well.

**Comment by kerri-augenstein** [comment]
Closing this ticket, resolved to two new tickets. 

Linked Card: #430 
A variant of card that allows for the image, headline, and background of the card to all be a single link together, with hoverstates included. 

Add Link to Headline in Card: #453
Add the option for a headline to include a link.
