### ISSUE TITLE
add same animation to more-link as exists for action-link

### ISSUE THREAD

**Issue by JBCSU** [SU-SWS/decanter#355]
When you hover over a `.su-link--action`, the little arrow in `:after` moves smoothly a few px to the right. I think the little double-arrow after `.su-link--more` should do the same. Should the icon after `.su-link--external` also move?

**Comment by yvonnetangsu** [comment]
Yeah, good question. John was saying he had some animation in mind, e.g., the external icon would move 45 degree to the top right slightly when hovered over. He might not have a chance to document those before he left because it wasn't a priority...let me see if I can find anything about that. @josephgknox, did John mention to you and Kerri about the link icon animations? 🤔

**Comment by josephgknox** [comment]
This wasn't documented, nor do I recall being part of a discussion specifically on this. I'm 100% behind the idea, though. It is something that we (or I) can bring up with Kerri, though.
