### ISSUE TITLE
What can we poach from an accessible pattern library WhatSock

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/decanter#392]
Have a review of http://whatsock.com/tsg/ for items that may be of use for us to poach. Please add to the comments of this ticket anything you identified as potential.

**Comment by yvonnetangsu** [comment]
I need some more time to look at the whatsock page, but I attended a workshop hosted by Deque labs and I like how they handle modal window tab order. Every modal has a title which would be the first thing on focus when a keyboard user opens a modal (and the title will be announced in the SR), then as they tab, it moves focus to the "x" close button so they can close it right away if they find it irrelevant. After that it cycles through the focusable elements inside the modal content and any buttons at the bottom, then it goes back to the top "x" close button (skipping the title in the > 1 rounds since there's no need to announce the title twice) and then back to the content again.

https://pattern-library.dequelabs.com/composites/modals

Unfortunately they use React but I think we can get some ideas at least :)
