### ISSUE TITLE
Typographic styles tweaks + adds

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#490]
**Tweak**

.su-caption Caption Font
change from 
1.8rem 
to 
1.6 rem

.su-credits Credits Font
change from 
1.8rem 
to 
1.6rem 

**Add**
Display A-F so that they appear in the Typography section of Decanter, under "Elements"

**Comment by yvonnetangsu** [comment]
@kerri-augenstein , is it possible to make Credits italic instead of Caption? (currently caption is in italic) Currently on news.stanford.edu, we have the credits in italic while the caption is regular. And this would allow for the occasional chance that people want to make a few words italic in the caption.

**Comment by kerri-augenstein** [comment]
@yvonnetangsu feel free to make that change! In Drupal we use a single "caption/credit" field, and let authors decide how they want to use italics/bold/urls with a minimal wysiwyg.
