### ISSUE TITLE
Page Content and Children: Brand

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#575]
https://elegant-poitras-87214a.netlify.com/page/brand-design-elements-brand/

this page and everything under it needs to be drafted. Do we want to link to identity.stanford.edu for most of this?

**Comment by yvonnetangsu** [comment]
@buttonwillowsix , I'm looking at the Color page, and I'm thinking that perhaps we don't want to link out to identity for this because we probably want to include the color variable names here (which wouldn't make sense on the Identity site) and also add links to the color related mixins.

**Comment by buttonwillowsix** [comment]
Color inspiration: https://etrade.design/colors

**Comment by yvonnetangsu** [comment]
@buttonwillowsix I'm debating on adding some colors to the color page. I know some of our existing colors (e.g., the beige colors) will be gone very soon, and some I need to confirm with Dana whether we're adding back in (eg., the chocolate color). I didn't add the colors that I know will be gone for sure because I don't want to encourage people to use them and then they'll have to change them out in a couple months 🤔

**Comment by yvonnetangsu** [comment]
And I'll steal some text from the SOAP page about accessibility and link out to their page, and add the mixin info.

**Comment by buttonwillowsix** [comment]
@kerri-augenstein and @yvonnetangsu I think the main thing left to do here is the icons, and also to remember later to update colors.
If you agree, I suggest we:

- Close this issue
- Add a new ticket for icon documentation in our Documentation project
- Add a new ticket to update the color page

Thoughts?

**Comment by kerri-augenstein** [comment]
@buttonwillowsix, totally agreed. 

Icon ticket added: 
https://github.com/SU-SWS/decanter/issues/610

Update color page ticket: 
https://github.com/SU-SWS/decanter/issues/611

**Comment by kerri-augenstein** [comment]
Closing this ticket.
