### ISSUE TITLE
Update colors on Color page when Identity is complete

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#611]
https://decanter.stanford.edu/page/brand-design-elements-color/

**Comment by buttonwillowsix** [comment]
@yvonnetangsu also said she will add additional color documentation

**Comment by yvonnetangsu** [comment]
I'm going to start a PR to add the new Identity Guide colors to Decanter v6. There are a few tricky ones though - 

For example, `$su-color-fog` - We still have a "Fog" color in the new palette, but it's a different color, and the original "Fog" gets renamed to "Fog Light" $su-color-fog-light (which is ok since we can do this update for our color maps). I'm more concerned about people using the $su-color-fog variable in their projects - when they update Decanter, it will become a different color.

I believe Stone and Cool Grey might be in the same boat as well (need to double check). 

What's the best way to handle something like this? @sherakama @katrialesser @jenbreese
