### ISSUE TITLE
Rationalize, update, & add new icons to Custom Icon Pack

### ISSUE THREAD

**Issue by kerri-augenstein** [SU-SWS/decanter#621]
Our current icon source files are all different sizes and canvas areas. We want to rationalize all of these files to be sourced from the same canvas size (24px sq), and for the designers to control the creation of the icons from Illustrator, so that they can tweak stroke widths and counter-forms to render properly. 

We want to replace all current icon source files with these new files. And tweak the display in all cases they appear in our patterns. 

You can find all of the svg files for the existing icons, and a family of new icons for our custom set in our Shared Google Drive folder here: 
https://drive.google.com/drive/folders/10mqEtttN13Awh2ze24kwassu3YRaCBNq

**Comment by yvonnetangsu** [comment]
These look really great! Thanks, @kerri-augenstein. Will need some dev testing as we want to make sure our current elements look the same when we switch to this new set (svg's are nice but they're tricky - doesn't behave the same way as regular images).

**Comment by cjwest** [comment]
Researching best practices here: https://github.com/SU-SWS/decanter/issues/751

**Comment by cjwest** [comment]
@kerri-augenstein, 
I could use an envelope icon for https://stanfordits.atlassian.net/browse/D8CORE-2950
I see that there's an .svg in this directory. Mike suggested I use a .png because it will be used in the editor. Any suggestions for making it happen?

Since my name is on this to bring into Decanter, I figure this is a good time to start!
Are all the icons in this directory ready to go:

https://drive.google.com/drive/u/1/folders/10mqEtttN13Awh2ze24kwassu3YRaCBNq

@sherakama,
What are the steps for adding the icons?

Do the icons just go into this directory
https://github.com/SU-SWS/decanter/tree/master/core/src/img

Is there anything else that needs to happen?

**Comment by kerri-augenstein** [comment]
@cjwest, 
All of the icons in the Drive SVG folder are ready to go! If you have a means of saving the email icon svg as a png, that's definitely the way forward. And let me know I can also do this!

**Comment by cjwest** [comment]
@kerri-augenstein,
I've never saved a svg as png. Is there any specific process or tool you recommend?

**Comment by kerri-augenstein** [comment]
@cjwest the tool I like to use is Illustrator. The process for saving a png is REALLY simple. 

You open the svg, and go to File > Export > Export as... 

Then hit "png" from the file option menu, and DONE! 

Our Adobe CC credentials are in confluence: 
https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials

If you have not used Adobe on your machine, you may need to download the most recent software by logging in and downloading: 
https://www.adobe.com/

_Special note: when you open Illustrator, you'll likely need to bump one of us out, don't worry about it, just go ahead and do so._
