### ISSUE TITLE
Form Hierarchy elements

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#647]
**Needs design**
- revisit spacers

**Dev notes**

**Design documentation**
[Form hierarchy](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=8380%3A1083)

**Comment by bhavikasolanki** [comment]
@kerri-augenstein I think this is for defining hierarchy in forms and providing the option to have sections. (Please let me know if I misinterpreted, @buttonwillowsix :) ) I saw that we have "Step Two: Your information"-type headings. Are there other helpers you've defined that I missed? If this needs design, what all should we offer? Some ideas that came to mind are horizontal rules and/or subtle shading of alternating sections, but I can also do some light researching to see how others define sections too. Thank you!!!

**Comment by kerri-augenstein** [comment]
@bhavikasolanki, there's also the Form Hierarchy section, where we have horizontal rules, white containers, and then also the light gray container (this one was super quick, and not fully fleshed out, as Brian had recently included this in his last form). 
https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=8380%3A1083

The "Step Two: Your Information"... is more about pagination within the form, and creating "progress" sections _I think_, but. @buttonwillowsix would breaking up forms into different pages be part of this "Field Group" definition?

**Comment by bhavikasolanki** [comment]
@kerri-augenstein 🤦‍♀️  how did I miss that? It's literally called Form Hierarchy. 😄  Thank you!!!

I know that Google forms allows you to add multiple steps/ progress sections on a page, which is nice when you have particularly short sections, but that doesn't mean we should/need to suit.

Pro: having multiple steps/ progress sections per page makes the form seem shorter for the user with the decreased number of pages, but
Con: might complicate the labels for the progress bar. I like how the number of bars corresponds with the number of pages and how you've labelled them; I'm not sure how we would label them if there are multiple steps/sections per page.

**Comment by kerri-augenstein** [comment]
@bhavikasolanki ahhh good point. Maybe part of the requirement if we create paginated progressive sections, is that there can only be one per "page"?

**Comment by bhavikasolanki** [comment]
Sounds good! We'll move forward with 1 section per page max, and I'll plan to include Headings as part of pagination rather than a hierarchical element.

As for the concern that users might assume that a form is longer because it has several pages: I wonder if we can communicate the length of the form with the progress bars. For example, if a page is short with only a few questions, the bar for that page appears shorter than the bars for other pages with more questions. What do you think?

An example of something similar to this is the progress bar in the [NYT Spelling Bee](https://www.nytimes.com/puzzles/spelling-bee), if you've ever played that. The yellow circle moves farther along the line if the word you've found is worth a greater number points. 
![Screen Shot 2020-09-18 at 3 21 55 AM](https://user-images.githubusercontent.com/42845005/93587068-2585f700-f95e-11ea-9c46-2f614e34fa8a.png)

**Comment by kerri-augenstein** [comment]
@bhavikasolanki oh that's an interesting suggestion!!!! I like that idea A LOT. 

I've never seen something like this implemented on forms. I wonder about a few things. 

- could we MVP with a basic progress indicator, but prototype something like you're talking about, and test it with users?
- how might we think through an author building that more complex progress indication?

**Comment by bhavikasolanki** [comment]
@kerri-augenstein Yay! and yes, definitely to MVPing with the basic progress indicator and prototyping/testing the other one. Excellent point about considering how an author might build the more complex progress indication. I had been imagining that the bar length might correspond to page length, and that this could be done through code. I'm not sure that this is technically possible, or how much time it might take if it is.

**Comment by kerri-augenstein** [comment]
@bhavikasolanki ahhhh that's definitely a possibility. I bet our developers could come up with some ideas on rigging this. Let's leave the idea in, draft a sketch, and shoot a question to Shea and Yvonne, see what they think off the bat.
