### ISSUE TITLE
Fix Lockup Options

### ISSUE THREAD

**Issue by buttonwillowsix** [SU-SWS/decanter#711]
.su-lockup--option-h is messed UP.

Remove lockups that are not approved

Change sample text to match what is on Decanter lockup documentation page (see Decanter Web for more info)

**Comment by yvonnetangsu** [comment]
@buttonwillowsix I actually have an answer to this one 😄  I remember option H was coded for only Engineering school in mind - basically only Engineering school was allowed to have their school name in that spot so the spacing and everything was tailored for that. Try replacing "Nameofschool" with "Engineering" and it will fit perfectly. Thanks for discovering this though because that means we need more documentation about this specific usage! 😂   But....with that said, I don't know if rules have changed now, ie, not sure if other schools are allowed to have their school name in that spot.

**Comment by yvonnetangsu** [comment]
I believe for schools with longer names, they were recommended to go with something like option J where the Stanford wordmark doesn't necessarily have the same width as the school name.

**Comment by sherakama** [comment]
Yea, that is why it is the way it is. 

We "fixed" this issue with some flexible css here: https://github.com/SU-SWS/stanford_basic/pull/170/files

We should probably roll it back up into Decanter so the wrapping happens instead of the breakage.
