### ISSUE TITLE
Adding "Accordion" lists to default template/website

### ISSUE THREAD

**Issue by Justin-at-Stanford** [SU-SWS/decanter#769]
I have a very basic question...how would I add, or enable, something like one of the three "Accordion" lists to an existing sites.stanford.edu website?

I'm trying to add one at siris.sites.stanford.edu/resources for FAQs.

Naively I thought perhaps I could paste code from the accordion twig (decanter/core/src/templates/components/accordion/accordion.twig) directly into the source code on the page and have it work immediately, but no.

I'm not entirely clear what is, and is not, allowed to be done through that basic source editing functionality with Stanford sites.
Thanks,
Justin

**Comment by sherakama** [comment]
Hey Justin,

Officially, there is nothing stopping you from adding the markup into your WYSIWYG on the Stanford sites platform and creating new features and functionality as found on the Decanter website. Unfortunately, we haven't moved everything from the Decanter project into the sites platform in a 1:1 way. Our WYSIWYG text formatters will also alter/strip some of the markup in an attempt to create valid/secure markup and may get in the way for attempting to do what you are doing. 

If you are looking to re-create the accordion I would suggest you use the HTML markup instead of the TWIG template and you might get a bit father.

**Comment by Justin-at-Stanford** [comment]
Thanks!

So I tried just editing things directly, but I don’t know enough about HTML to know why some pieces of code are ignored/stripped-out from what I put into it. Meaning, I’m not 100% sure where things are failing to work because the website template parameters are preventing things from being done, as opposed to simply I’ve coded something slightly wrong and so that’s why things don’t work.

Is there any chance we could do a short 5-minute zoom sometime? Perhaps I’ve grabbed the wrong snippet of code.
I’d like to recreate something similar to the accordion your group has sketched, but it certainly doesn’t have to be a 100% match or anything.

Thanks again,
Justin



Justin Lind
Student Analytics Educator/Analyst
Institutional Research & Decision Support
justinmh@stanford.edu<mailto:justinmh@stanford.edu>
Pronouns: he/him

**Comment by sherakama** [comment]
Hey Justin,

We have open office hours where you can get 1:1 support for your site. You can sign up for a spot here: https://stanford-web-services.appointlet.com/

**Comment by Justin-at-Stanford** [comment]
Thanks btw – I signed up for a slot next week


Justin

**Comment by sherakama** [comment]
Hello Justin,

My apologies but I mislead you. I have been corrected internally on that the office hours are not available for our free, self-service, customers. You can find lots of additional support on our userguide website at https://userguide.sites.stanford.edu/ and apply for help through Service Now at https://stanford.service-now.com/it_services?id=sc_cat_item&sys_id=abff87fa4f33f2009a9a97411310c723. 

Again, my apologies and best of luck.
